language: scala
scala:
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
- openjdk8
script:
- sbt coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_JDK_VERSION}" == "oraclejdk8"'
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: nXd+ZqfS1rvesKgjJvytuq8FfpyrcmN70r1lmGbjgSvsgcItIRAJ29yfb5SOTmtiLmHdKLyR680moeMlwbB+hWRFT/dPF36Mi1zQFuPHkXMo5g/F+WRDAbB7sBqneXg5Iu7auH8UZIk2qHR+cCXPTcRrw0CF+hgXuCFv5EBJvOFSdNkNkMIkpcWK/0mYNw+6sqdPCfgjA+qZknq3TvTPhwVKyzjffEJFk/jrQ12/s4Twy2wR9kz001yz97iE7N2Tb14fTGLId9DwhziahVb6EFSW/GlWZsI4BA5HNjpqmROvyPt66Kb9akG9Wmkng/sxG6SLRxLt8JmBzLvHXyynn+5Y57GRZ9EMuyknEXHU+05tgUoMqSyRa54i/3FyJMSXZH7ZaCGYQM2D8OGW22gdCes8NxFc/+tBZ+J3h7UgpeX3CaiXLg2n+FSwkuAbhNvyN/C5qqdWyDcMpsU+etVQ+hktmQ/sVzxSyAeG/VLe7prejTKzXVz9nP13xaNpvPvGRwD22idF9seur4GEPd5P6yhpu29t7dmuzsxCkZl8GjjOBwxfRE0UCjXA1WKypzrpHkd6BkU6WvaEnbtoOqv5eVD27sBdRoz8ZyAuG/erMx7NQTUYgAbGNo/YMpvj2DdnjOnU1vOO49GACfEbSyIB5vfy8H7qVDTUAlYpgbj/1wQ=
  - secure: kITLSV4PrEGTz4CcWydiQdvvlZuZt21cJmF++bLkwyspDofa9T3TE8rzvkWVmb4SNChU0PsiwTguMEQtGY8KTpZCjJGhNgAbrc9fTzQ26XIwaOW0HBvCMkv2N2NtEg7zKXZZ2BbEN5quXRsmtVw+OnBOFNskVHUkeR5CoeS3cFkNnm1V65VXpMkAbCtkQmPlyiIVkFgHNDx9jSOENFM7i/M1VIZwISr/QNqdA+qsnHW4ESkpNXPIca5LBp3LFIZTAWLemY3Awg8jckwBFq49WFim8+Vx0hpP9O/RVafULwNrYYBJTFWdQk3zKzLayPFYZ+xokIQTismUmIpAUcjfmsRD7grhzj2luzg1MYM4mgTXSd333r1eyLmDNz6ot1no5KzjX2ffq/XUKJdljkmhv/S9SQQeZrVVKojfmY9NsTZ52cb5onPYEURr4U3b8RiZ5ol2jf7x+3kU3BGFck6PccLaYzx8Xf0Ee0AXLX2FmQNTm7CTgK0rEvR4NqPx2OLXiwfFTj5AY2RrjwPFe9DqPm4xroCvMuqW+EwuZ+KJiK5F2VKgbBFoLPAGRYwMcoruogBqiPDl4a0tT3Jg15QmQcxR2my1BuZKw8hVF66anu2XnXKjvCda5VHMXtozI0gtUgHqjYcx2WBwGTQtabB2VBeDL0c99/+QtKVWf+FKk8A=
  - secure: NpWhOq+YL2wH+gB91Lnxs0yxuk7rjZlf2xMy51i6/b47qn8Eotqkzu2fxxvO+F/PqJen9GyXWyGaibAjXeMphYNU+/VaQMSgOAvggYi2vsNBqlJnf/1CEN1+ZThpXHROjsMC3ux1w53YzJHP2eTgKdtIwHW9WYszc3BMWBnzWVnXsHGaugimAxkMnyQAqUOw/5MqGNq6K1/DEBW4iy2K2a2LB8siZOcNIx9HR3atoZZkwxXVHUW6EKyAu4RbyHRADBqkAURt1HeAwIU4ijJsFJajvZcBzA7chZ4CuKxHQwZ1ivY1GgTj2nm0MtChl66hSgfO30CZVQodiNA/xL3YlD3PAYWeWpL3TZciJAl4iYC4pqlYXRYCEpbhGCZGemTt5/PjOFgwyWpI8I4DvvSlEe58WocvLEa1+sBP9zrZR+VcrUtBUjuD/11lQePV1tfv3oCcJlfAijTa9POgiBy2lmo2JGxoUeGF7eAEN8VxnLSS2AfP09u7PF42XNe66sWRMjE6C2/TrIcUn70rSI8NnF5APtbGMWXW6+lyrge/7TWPU+KNMaaTVlbFkjubyKETfq7dieyGNlXL+g8g3BgVjBJg6ccb71UrmD2qmPsvzhN5Z5L6zt5kN+YzjMVZjUeoSpyneV3e0ricsgsQ3Xn+vDoDIbH87Lz5zIqiYsZb/Yw=
